services:
  - type: web
    name: biomedical-backend
    env: java
    plan: free
    buildCommand: ./gradlew clean bootJar -x test --no-daemon
    startCommand: java -jar build/libs/*.jar
    rootDirectory: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512M

